models:
  - name: dim_orders
    columns:
      - name: order_key
        tests:
          - not_null
          - unique
  - name: dim_line_items
    columns:
      - name: order_item_key
        tests: 
          - not_null
          - unique
        
